   export const vehicleData :any= [
  {
    "VIN": "5YJYGDEE1L",
    "County": "King",
    "City": "Seattle",
    "State": "WA",
    "Postal Code": "98122",
    "Model Year": 2020,
    "Make": "TESLA",
    "Model": "MODEL Y",
    "Electric Vehicle Type": "Battery Electric Vehicle (BEV)",
    "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Electric Range": 291,
    "Base MSRP": 0,
    "Legislative District": 37,
    "DOL Vehicle ID": 125701579,
    "Vehicle Location": "POINT (-122.30839 47.610365)",
    "Electric Utility": "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
    "2020 Census Tract": "53033007800"
  },
  {
    "VIN": "7SAYGDEE9P",
    "County": "Snohomish",
    "City": "Bothell",
    "State": "WA",
    "Postal Code": "98021",
    "Model Year": 2023,
    "Make": "TESLA",
    "Model": "MODEL Y",
    "Electric Vehicle Type": "Battery Electric Vehicle (BEV)",
    "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "Eligibility unknown as battery range has not been researched",
    "Electric Range": 0,
    "Base MSRP": 0,
    "Legislative District": 1,
    "DOL Vehicle ID": 244285107,
    "Vehicle Location": "POINT (-122.179458 47.802589)",
    "Electric Utility": "PUGET SOUND ENERGY INC",
    "2020 Census Tract": "53061051938"
  },
  {
    "VIN": "5YJSA1E4XK",
    "County": "King",
    "City": "Seattle",
    "State": "WA",
    "Postal Code": "98109",
    "Model Year": 2019,
    "Make": "TESLA",
    "Model": "MODEL S",
    "Electric Vehicle Type": "Battery Electric Vehicle (BEV)",
    "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Electric Range": 270,
    "Base MSRP": 0,
    "Legislative District": 36,
    "DOL Vehicle ID": 156773144,
    "Vehicle Location": "POINT (-122.34848 47.632405)",
    "Electric Utility": "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
    "2020 Census Tract": "53033006800"
  },
  {
    "VIN": "5YJSA1E27G",
    "County": "King",
    "City": "Issaquah",
    "State": "WA",
    "Postal Code": "98027",
    "Model Year": 2016,
    "Make": "TESLA",
    "Model": "MODEL S",
    "Electric Vehicle Type": "Battery Electric Vehicle (BEV)",
    "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Electric Range": 210,
    "Base MSRP": 0,
    "Legislative District": 5,
    "DOL Vehicle ID": 165103011,
    "Vehicle Location": "POINT (-122.03646 47.534065)",
    "Electric Utility": "PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)",
    "2020 Census Tract": "53033032104"
  },
  {
    "VIN": "5YJYGDEE5M",
    "County": "Kitsap",
    "City": "Suquamish",
    "State": "WA",
    "Postal Code": "98392",
    "Model Year": 2021,
    "Make": "TESLA",
    "Model": "MODEL Y",
    "Electric Vehicle Type": "Battery Electric Vehicle (BEV)",
    "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "Eligibility unknown as battery range has not been researched",
    "Electric Range": 20,
    "Base MSRP": 0,
    "Legislative District": 23,
    "DOL Vehicle ID": 205138552,
    "Vehicle Location": "POINT (-122.55717 47.733415)",
    "Electric Utility": "PUGET SOUND ENERGY INC",
    "2020 Census Tract": "53035940100"
  },
  {
    "VIN": "1N4AZ1CP0K",
    "County": "Thurston",
    "City": "Olympia",
    "State": "WA",
    "Zip": "98501",
    "Year": 2019,
    "Make": "NISSAN",
    "Model": "LEAF",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 150,
    "FuelCostSavings": 0,
    "TotalChargingStations": 22,
    "EIAId": 347436820,
    "Coordinates": "POINT (-122.89692 47.043535)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53067011721
  },
  {
    "VIN": "5YJ3E1EB0N",
    "County": "Thurston",
    "City": "Olympia",
    "State": "WA",
    "Zip": "98513",
    "Year": 2022,
    "Make": "TESLA",
    "Model": "MODEL 3",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Eligibility unknown as battery range has not been researched",
    "Range": 0,
    "FuelCostSavings": 0,
    "TotalChargingStations": 2,
    "EIAId": 205746894,
    "Coordinates": "POINT (-122.817545 46.98876)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53067011624
  },
  {
    "VIN": "WMEFJ9BA8H",
    "County": "Thurston",
    "City": "Olympia",
    "State": "WA",
    "Zip": "98502",
    "Year": 2017,
    "Make": "SMART",
    "Model": "FORTWO",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 58,
    "FuelCostSavings": 0,
    "TotalChargingStations": 22,
    "EIAId": 257247357,
    "Coordinates": "POINT (-122.92145 47.045935)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53067012002
  },
  {
    "VIN": "1N4AZ0CP1D",
    "County": "King",
    "City": "Shoreline",
    "State": "WA",
    "Zip": "98155",
    "Year": 2013,
    "Make": "NISSAN",
    "Model": "LEAF",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 75,
    "FuelCostSavings": 0,
    "TotalChargingStations": 32,
    "EIAId": 221188747,
    "Coordinates": "POINT (-122.3175 47.7578146)",
    "Utility": "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
    "UtilityId": 53033020500
  },
  {
    "VIN": "5YJ3E1EA5L",
    "County": "Thurston",
    "City": "Rochester",
    "State": "WA",
    "Zip": "98579",
    "Year": 2020,
    "Make": "TESLA",
    "Model": "MODEL 3",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 266,
    "FuelCostSavings": 0,
    "TotalChargingStations": 20,
    "EIAId": 128514494,
    "Coordinates": "POINT (-123.09575 46.82114)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53067012730
  },
  {
    "VIN": "WBY1Z4C54F",
    "County": "King",
    "City": "Seattle",
    "State": "WA",
    "Zip": "98144",
    "Year": 2015,
    "Make": "BMW",
    "Model": "I3",
    "Type": "Plug-in Hybrid Electric Vehicle (PHEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 72,
    "FuelCostSavings": 0,
    "TotalChargingStations": 37,
    "EIAId": 257160480,
    "Coordinates": "POINT (-122.30823 47.581975)",
    "Utility": "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
    "UtilityId": 53033009500
  },
  {
    "VIN": "5YJ3E1EA1J",
    "County": "Snohomish",
    "City": "Bothell",
    "State": "WA",
    "Zip": "98021",
    "Year": 2018,
    "Make": "TESLA",
    "Model": "MODEL 3",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 215,
    "FuelCostSavings": 0,
    "TotalChargingStations": 1,
    "EIAId": 476172749,
    "Coordinates": "POINT (-122.179458 47.802589)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53061051926
  },
  {
    "VIN": "5YJ3E1EB7K",
    "County": "Thurston",
    "City": "Tenino",
    "State": "WA",
    "Zip": "98589",
    "Year": 2019,
    "Make": "TESLA",
    "Model": "MODEL 3",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 220,
    "FuelCostSavings": 0,
    "TotalChargingStations": 35,
    "EIAId": 207105636,
    "Coordinates": "POINT (-122.85403 46.856085)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53067012610
  },
  {
    "VIN": "KNDCD3LD2J",
    "County": "Snohomish",
    "City": "Edmonds",
    "State": "WA",
    "Zip": "98020",
    "Year": 2018,
    "Make": "KIA",
    "Model": "NIRO",
    "Type": "Plug-in Hybrid Electric Vehicle (PHEV)",
    "Eligibility": "Not eligible due to low battery range",
    "Range": 26,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 474854215,
    "Coordinates": "POINT (-122.37507 47.80807)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53061050501
},
{
    "VIN": "JTDKARFP5K",
    "County": "Thurston",
    "City": "Olympia",
    "State": "WA",
    "Zip": "98501",
    "Year": 2019,
    "Make": "TOYOTA",
    "Model": "PRIUS PRIME",
    "Type": "Plug-in Hybrid Electric Vehicle (PHEV)",
    "Eligibility": "Not eligible due to low battery range",
    "Range": 25,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 231185076,
    "Coordinates": "POINT (-122.89692 47.043535)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53067010400
},
{
    "VIN": "5UXTS1C01M",
    "County": "Thurston",
    "City": "Olympia",
    "State": "WA",
    "Zip": "98501",
    "Year": 2021,
    "Make": "BMW",
    "Model": "X3",
    "Type": "Plug-in Hybrid Electric Vehicle (PHEV)",
    "Eligibility": "Not eligible due to low battery range",
    "Range": 17,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 223772797,
    "Coordinates": "POINT (-122.89692 47.043535)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53067010300
},
{
    "VIN": "1N4BZ1CP3K",
    "County": "Thurston",
    "City": "Olympia",
    "State": "WA",
    "Zip": "98502",
    "Year": 2019,
    "Make": "NISSAN",
    "Model": "LEAF",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 150,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 109584044,
    "Coordinates": "POINT (-122.92145 47.045935)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53067010600
},
{
    "VIN": "KNDJX3AE5G",
    "County": "Snohomish",
    "City": "Edmonds",
    "State": "WA",
    "Zip": "98020",
    "Year": 2016,
    "Make": "KIA",
    "Model": "SOUL",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 93,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 158961099,
    "Coordinates": "POINT (-122.37507 47.80807)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53061050700
},
{
    "VIN": "1N4BZ0CP5H",
    "County": "Chelan",
    "City": "Wenatchee",
    "State": "WA",
    "Zip": "98801",
    "Year": 2017,
    "Make": "NISSAN",
    "Model": "LEAF",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 107,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 110066176,
    "Coordinates": "POINT (-120.32009 47.42255)",
    "Utility": "PUD NO 1 OF CHELAN COUNTY",
    "UtilityId": 53007961102
},
{
    "VIN": "5YJ3E1EB3K",
    "County": "Kitsap",
    "City": "Kingston",
    "State": "WA",
    "Zip": "98346",
    "Year": 2019,
    "Make": "TESLA",
    "Model": "MODEL 3",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 220,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 334167431,
    "Coordinates": "POINT (-122.50156 47.8019)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53035090101
},
{
    "VIN": "KNDCE3LG3K",
    "County": "Thurston",
    "City": "Olympia",
    "State": "WA",
    "Zip": "98502",
    "Year": 2019,
    "Make": "KIA",
    "Model": "NIRO",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 239,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 312765582,
    "Coordinates": "POINT (-122.92145 47.045935)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53067011100
},
{
    "VIN": "5YJXCBE22J",
    "County": "King",
    "City": "Seattle",
    "State": "WA",
    "Zip": "98101",
    "Year": 2018,
    "Make": "TESLA",
    "Model": "MODEL X",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 238,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 474870861,
    "Coordinates": "POINT (-122.335345 47.61079)",
    "Utility": "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
    "UtilityId": 53033008102
},
{
    "VIN": "5YJ3E1EA2J",
    "County": "Snohomish",
    "City": "Mukilteo",
    "State": "WA",
    "Zip": "98275",
    "Year": 2018,
    "Make": "TESLA",
    "Model": "MODEL 3",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 215,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 336812472,
    "Coordinates": "POINT (-122.299965 47.94171)",
    "Utility": "PUGET SOUND ENERGY INC",
    "UtilityId": 53061041301
},
{
    "VIN": "5YJ3E1EB3K",
    "County": "King",
    "City": "Seattle",
    "State": "WA",
    "Zip": "98109",
    "Year": 2019,
    "Make": "TESLA",
    "Model": "MODEL 3",
    "Type": "Battery Electric Vehicle (BEV)",
    "Eligibility": "Clean Alternative Fuel Vehicle Eligible",
    "Range": 220,
    "FuelCostSavings": 0,
    "TotalChargingStations": 0,
    "EIAId": 212077288,
    "Coordinates": "POINT (-122.34848 47.632405)",
    "Utility": "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
    "UtilityId": 53033007203
},
]
